### ISSUE TITLE
Navnekonvensjon i Java er at klasser har StorForbokstav

### ISSUE THREAD

**Issue by jhannes** [Westerdals/yatzyassignment#1]
https://github.com/Westerdals/pgr203-assignment-1-iaffs/blob/a60e452fc511911bbbfd13359c23a1687334f13f/src/test/java/no/forelesning/yatzyJava/test.java#L7

Det er også viktigere å ha mer beskrivende navn enn "test". For eksempel RomanTest

**Comment by iaffs** [comment]
Jeg skjønner.
