### ISSUE TITLE
Denne vil vel gi galt svar på for eksempel new int[] { 6, 6, 1, 1, 2 } ?

### ISSUE THREAD

**Issue by jhannes** [Westerdals/yatzyassignment#3]
https://github.com/Westerdals/pgr203-assignment-1-iaffs/blob/17fe08f9d1cc439b7e09d87245bce8d16444faba/src/main/java/no/forelesning/yatzyJava/Yatzy.java#L203

**Comment by iaffs** [comment]
Det må jeg se nærmere på. Men jeg betviler deg ikke, du har nok rett.
